# Sample cloudbuild.yaml that can containerize a Java app with JFrog Artifactory as a source of truth.
# NOTE: JFrog cloud builder image should exist. cloudbuild.yaml to build JFrog cloud builder image exists one level up.

# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml


steps:

# Configure JFrog CLI to point to JFrog Artifactory
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'c', 'art-repo', '--url=${_ARTIFACTORY_URL}', '--user=${_USER}', '--password=${_PASSWORD}']
  env:
    - "JFROG_CLI_TEMP_DIR=./"
    - "JFROG_CLI_HOME_DIR=./"
  id: 'setup_environment'

# Lint Helm chart
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: [ '-c', 'helm lint go-service' ]
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'lint_helm_chart'
  waitFor:
  - 'setup_environment'

# Build Helm chart
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: [ '-c', 'helm package go-service --save=false' ]
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'build_helm_chart'
  waitFor:
  - 'lint_helm_chart'

# Push Helm chart to JFrog Artifactory using JFrog CLI
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'u', 'go-service*.tgz', '${_HELM_REPO}', '--build-name=${_BUILD_NAME}', '--build-number=$BUILD_ID',]
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'push_helm_chart'
  waitFor:
  - 'build_helm_chart'

# Capture Build Information
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bce', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'capture_build_info'
  waitFor:
  - 'push_helm_chart'

# Publish Build Information to Artifactory
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bp', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'publish_build_info'
  waitFor:
  - 'capture_build_info'

# Scan Build using JFrog Xray
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bs', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'xray_scan_build'
  waitFor:
  - 'publish_build_info'

# Promote Build
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bpr', '${_BUILD_NAME}', '$BUILD_ID', '${_HELM_PROD_REPO}','--status=Released', '--comment=Tested.', '--copy=true' ]
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'promote_build'
  waitFor:
  - 'xray_scan_build'