# Sample cloudbuild.yaml that can containerize a Java app with JFrog Artifactory as a source of truth.
# NOTE: JFrog cloud builder image should exist. cloudbuild.yaml to build JFrog cloud builder image exists one level up.

# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml


steps:

# Configure JFrog CLI to point to JFrog Artifactory
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'c', 'art-repo', '--url=${_ARTIFACTORY_URL}', '--user=${_USER}', '--password=${_PASSWORD}']
  env:
    - "JFROG_CLI_TEMP_DIR=./"
    - "JFROG_CLI_HOME_DIR=./"
  id: 'setup_environment'

# Run Test
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['test']
  env: ['PROJECT_ROOT=github.com/jainishshah17/containerize-go-microservice']
  id: 'build_test_app'

# build docker image with two tags:
# latest and commit sha
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--rm'
  - '--no-cache'
#  - '--tag=${_ART_DOCKER_REGISTRY}/containerize-go-microservice:latest'
  - '--tag=${_ART_DOCKER_REGISTRY}/containerize-go-microservice:$BUILD_ID'
  - '.'
  id: 'containerize_app'
  waitFor:
  - 'build_test_app'


# Push docker image to JFrog Artifactory using JFrog CLI
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'docker-push', '${_ART_DOCKER_REGISTRY}/containerize-go-microservice:$BUILD_ID', '${_DOKCER_VIRTUAL_REPO}', '--build-name=${_BUILD_NAME}', '--build-number=$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'push_static_tag'
  waitFor:
  - 'containerize_app'

## Push latest docker image to JFrog Artifactory using JFrog CLI
#- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
#  args: ['rt', 'docker-push', '${_ART_DOCKER_REGISTRY}/containerize-go-microservice:latest', '${_DOKCER_VIRTUAL_REPO}', '--build-name=${_BUILD_NAME}', '--build-number=$BUILD_ID']
#  env:
#  - "JFROG_CLI_TEMP_DIR=./"
#  - "JFROG_CLI_HOME_DIR=./"
#  id: 'push_dynamic_tag'
#  waitFor:
#  - 'push_static_tag'

# Capture Build Information
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bce', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'capture_build_info'
  waitFor:
  - 'push_static_tag'

# Publish Build Information to Artifactory
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bp', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'publish_build_info'
  waitFor:
  - 'capture_build_info'

# Scan Build using JFrog Xray
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bs', '${_BUILD_NAME}', '$BUILD_ID']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'xray_scan_build'
  waitFor:
  - 'publish_build_info'

# Promote Build
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  args: ['rt', 'bpr', '${_BUILD_NAME}', '$BUILD_ID', '${_DOCKER_PROD_REPO}','--status=Released', '--comment=Tested.' , '--copy=true']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'promote_build'
  waitFor:
  - 'xray_scan_build'