# Sample cloudbuild.yaml that can containerize a Java app with JFrog Artifactory as a source of truth.
# NOTE: JFrog cloud builder image should exist. cloudbuild.yaml to build JFrog cloud builder image exists one level up.

# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

# Prepare AQL Query
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: ['-c', 'sed -E "s/VERSION/${_BUNDLE_VERSION}/g; s/ART_ID/${_SOURCE_ART_ID}/g; s/HELM_CHART/${_HELM_CHART}/g; s/DOCKER_TAG/${_DOCKER_IMAGE_TAG}/g" .pipeline/releaseBundle.json > .pipeline/bundle.json']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'prepare_aql_query'

# Create Release Bundle
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: [ '-c', 'curl -X POST -u ${_USER}:${_PASSWORD} -H "Content-Type: application/json" ${_DIST_URL}/api/v1/release_bundle -T .pipeline/bundle.json']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'create_release_bundle'
  waitFor:
  - 'prepare_aql_query'

# Sign Release Bundle
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: [ '-c', 'curl -X POST -H "Content-Type: application/json" -u ${_USER}:${_PASSWORD} ${_DIST_URL}/api/v1/release_bundle/go-service/${_BUNDLE_VERSION}/sign']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'sign_release_bundle'
  waitFor:
  - 'create_release_bundle'

# Distribute Release Bundle To Edge Nodes
- name: 'jainishshah17/google-cloud-builder-docker:1.22.1'
  entrypoint: 'bash'
  args: [ '-c', 'curl -X POST -H "Content-Type: application/json" -u ${_USER}:${_PASSWORD} ${_DIST_URL}/api/v1/distribution/go-service/${_BUNDLE_VERSION} -T .pipeline/distribution.json']
  env:
  - "JFROG_CLI_TEMP_DIR=./"
  - "JFROG_CLI_HOME_DIR=./"
  id: 'distribute_release_bundle'
  waitFor:
  - 'sign_release_bundle'